### ISSUE TITLE
FAILURE_ACCURACY_NOT_MET

### ISSUE THREAD

**Issue by eeelkhan** [synopsys-sig/synopsys-action#220]
Hey!

I am getting `Extraction for NPM Package Json Parse has accuracy of LOW but HIGH is required by the current detect.accuracy.required configuration.` when running on javascript (frontend)  project.
Workflow was a copypaste from the BlackDuck docs. And I don't see how `detect.accuracy.required` can be set.

**Comment by eeelkhan** [comment]
I am running BlackDuck in a monorepo with multiple projects (single BlackDuck project setup) and I am also wondering if `detect.detector.depth` needs to be passed somehow.

**Comment by eeelkhan** [comment]
For anyone bumping into this:
```
 env:
          DETECT_PROJECT_NAME: ${{ inputs.detect_project_name }}
          DETECT_DETECTOR_DEPTH: "5"
          DETECT_ACCURACY_REQUIRED: "NONE"
```
