### ISSUE TITLE
synopsys-sig/synopsys-action not scanning scala code

### ISSUE THREAD

**Issue by sanararoj** [synopsys-sig/synopsys-action#229]
We are using a bunch of git repositories with C#, Python and Scala languages.

As initial and simply approach we are using th synopsys-action like this
````
coverity:
    runs-on: orchestrator-runner
    if: github.repository == 'GridEdgeLoB-SM/ecostruxure-gme-ui'
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Run Coverity Analysis
        uses: synopsys-sig/synopsys-action@10044b457c8e47c18f58be717953bd992411df97 # v1.5.0
        with:
          coverity_url: ${{ env.COVERITY_URL }}
          coverity_user: ${{ env.COVERITY_USER }}
          coverity_passphrase: ${{ env.COVERITY_PASSPHRASE }}
          coverity_project_name: ${{ github.event.repository.name }}
          coverity_stream_name: ${{ format('{0}-{1}', github.event.repository.name, ((github.event_name == 'push' && github.ref_name) || (github.event_name == 'pull_request' && github.base_ref))) }}
          coverity_local: true
````

![image](https://github.com/synopsys-sig/synopsys-action/assets/64697155/51a9ffcc-27db-4a2d-84ca-0264f7ccb34f)

![image](https://github.com/synopsys-sig/synopsys-action/assets/64697155/9a179636-8e82-4e33-97ec-4336326496e5)

As you can noticed in the pictures C# and Python files are detected and scanned, we can even see the _security issues_ in the coverity portal

However, Scala files that are in the same GIT HUB workspace are not being picked by the coverity scan.

Is this action actually supporting the scanning of Scala files ?

Best regards
