### ISSUE TITLE
No findings, errors or warnings, when scan is used in RAPID mode

### ISSUE THREAD

**Issue by mihbatista** [synopsys-sig/synopsys-action#235]
Issue
----
The `synopsis-action:1.11.0` executes successfully **in RAPID mode** but **no errors & warnings are found**, even though we see in the reports generated by the `intelligent` scan that there are actually some security, license or operational risks.

The same behaviour of the RAPID scan can be observed for our both android & ios codebases.

Expected result
----
- Findings are reported also in RAPID mode

Current setup - Android
----
**Github Action: snippet of the synopsis action setup**
```
 - name: Export Blackduck args
   shell: bash
   run: |
      # Export the Blackduck args for the next step
      echo "BLACKDUCK_ARGS=
      --detect.excluded.detector.types=NPM
      --detect.required.detector.types=GIT,GRADLE
      --detect.excluded.directories=core,.bridge
      --detect.gradle.included.configurations=prodApiReleaseRuntimeClasspath
      --detect.project.version.name=$APP_VERSION" >> "$GITHUB_ENV"

- name: Black Duck Scan
   uses: synopsys-sig/synopsys-action@c5ee7cdaa0b274794c2ba9faca143e6fa9c10ac1 # v1.11.0
   env:
      DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
      DETECT_BLACKDUCK_RAPID_COMPARE_MODE: ALL
   with:
      blackduck_url: ${{ vars.BLACKDUCK_HOST_URL }}
      blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
      blackduck_scan_full: false
      blackduck_prcomment_enabled: true
      blackduck_scan_failure_severities: 'ALL'
      github_token: ${{ secrets.GITHUB_TOKEN }}
      blackduck_args: ${{ steps.args.outputs.BLACKDUCK_ARGS }}
```

The given args, env vars and inputs are picked up correctly by the action, below is an excerpt from the logs.

**Job logs: detect configuration**
```
- gradle-8.4
- synopsis-action:1.11.0
- detect: 9.8
- blackduck.offline.mode = false [cmd] 
- detect.bdio.file.name = scan [cmd] 
- detect.bdio.output.path = /home/...bridge/Blackduck Detect Execution/detect/bdio/blackduck_artifact [cmd] 
- detect.blackduck.rapid.compare.mode = ALL [env] 
- detect.blackduck.scan.mode = RAPID [cmd] 
- detect.cleanup = false [cmd] 
- detect.excluded.detector.types = NPM [env] 
- detect.excluded.directories = /home/runner/work/***-***-android/***-***-android/.bridge [env] 
- detect.gradle.included.configurations = prodApiReleaseRuntimeClasspath [env] 
- detect.output.path = /home/runner/work/***-***-android/***-***-android/.bridge/Blackduck Detect Execution/detect [cmd] 
- detect.project.name = ***-***-android [env] 
- detect.project.version.name = 3.3.0 [env] 
- detect.required.detector.types = GIT,GRADLE [env] 
```

**Job logs: results** 
```
Rapid Scan Result Details:
Components Errors: 
Components Warnings: 
Security Errors: 
Security Warnings: 
License Errors: 
License Warnings: 
Other Errors: 
Other Warnings: 

Creating status file: /home/runner/work/***-***-android/***-***-android/.bridge/Blackduck Detect Execution/detect/runs/2024-07-19-10-59-21-575/status/status.json
 
Skipping cleanup, it is disabled.

 ======== Detect Result ========

Rapid Scan Result: (for more detail look in the log for Rapid Scan Result Details)
	
Critical and blocking policy violations for
			* Components: 0
			* Security: 0
			* License: 0
			* Other: 0
	
		Other policy violations
			* Components: 0
			* Security: 0
			* License: 0
			* Other: 0
	
		Policies Violated:
	
		Components with Policy Violations:
	
		Components with Policy Violation Warnings:

======== Detect Status ========

GIT: SUCCESS
GRADLE: SUCCESS
Overall Status: SUCCESS - Detect exited successfully.
```

The full logs of the RAPID scan step:
[synopsis-action-logs-v1.11.0.txt](https://github.com/user-attachments/files/16311465/synopsis-action-logs-v1.11.0.txt)

Please let me know in case I can provide additional info or try a particular configuration. Also please let me know if you need details related to the iOS setup.

Thank you, 
Best regards,
Mihai
