### ISSUE TITLE
Commiting coverity scan results on Connect server

### ISSUE THREAD

**Issue by lzo2** [synopsys-sig/synopsys-action#252]
When running this action v1.13.0, I can fully scan my project source code with coverity and the results are generated locally. Everything works fine and wow I need to upload the result on the company Connect server.
Is there any option to execute the Coverity Connect Commit step with that github action, or should I add a new step to manually execute a `coverity commit`. Any tips for commiting results is welcome

Thanks and regards
-Lzo

```yaml
      # SCA - Coverity using synopsys-action@1.13.0
      - name: Coverity Full Scan
        uses: synopsys-sig/synopsys-action@2b8476cc491cd5515ee04e3c215698bfd8523504
        with:
          ### Coverity Connect users
          coverity_local: true

          ### Scanning required fields
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ vars.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: ${{ github.event.repository.name }}
          coverity_stream_name: ${{ github.event.repository.name }}-master
          coverity_policy_view: 'Outstanding Issues'

          ### Arbitrary product-related CL arguments
          coverity_build_command: cmake --build ./build --target all
          coverity_clean_command: cmake --build ./build --target clean
```
